# Airbnb ESLint rules

env:
  browser: true
  es6: true
extends: 'airbnb'
rules:
  no-cond-assign: off
  no-param-reassign: off
  no-restricted-properties: off
  no-return-assign: off
  no-use-before-define: off
  prefer-rest-params: off
  prefer-template: off
  react/no-this-in-sfc: off
  valid-typeof: off